name: Pull Request Autoresponse

on:
  pull_request:
    types: [opened]

jobs:
  auto-response:
    runs-on: ubuntu-latest

    steps:
    - uses: derekprior/add-autoresponse@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        respondableId: ${{ github.event.pull_request.node_id }}
        response: "Thank you for your contribution. Please note that, as we are currently working on solutions to help face the current crisis, we do not have the capacity to manage any pull requests."
        author: ${{ github.event.pull_request.user.login }}
